### ISSUE TITLE
deploy_packages.pp correct aem_id handling

### ISSUE THREAD

**Issue by mbloch1986** [shinesolutions/puppet-aem-resources#27]
The deploy artifacts has a logic inside, which sets the aem_id to the aem_id set in the descriptor file. 

Since the descriptor file contains not always a aem_id, it needs to be set whether to the parameter from the hiera file or default 'author'. A realistic scenario where the aem_id is going to be set in the descriptor file is the consolidated instance.

**Comment by mbloch1986** [comment]
Following code line is infected:

  $packages.each | Integer $index, Hash $package| {

    $aem_id = $package[aem_id]

    $final_sleep_seconds = pick(
      $package['sleep_seconds'],
      $sleep_seconds,
    )

**Comment by cliffano** [comment]
Done. Included in 2.2.2 .
