### ISSUE TITLE
Use SSL for Author-Standby data sync

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/puppet-aem-resources#69]
Data sync for AEM Author-Standby currently defaults to secure setting to false https://github.com/shinesolutions/puppet-aem-resources/blob/master/templates/StandbyStoreService.config.epp#L5.
We need to test data sync via SSL with secure setting set to true, and then set that as the default .

**Comment by mbloch1986** [comment]
I've tested the data sync between Author-Primary <-> Author-Standby with SSL enabled and the tests were successfully. After promoting the author-standby as a primary I was able to see the page changes. 

The error.log of the author-standby instance also showed that the sync was working correct.

**Comment by mbloch1986** [comment]
SSL encryption is enabled since puppet-aem-resources 6.0.0
